DELETE http://localhost:8080/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzQ0MDY0OTA4LCJ1c2VySWQiOjF9.AbDWk_ixCiuTY9YrzrgKr_Dwoy608dY3ziDDRcrHUUM
